package com.carl.springmvc.model;

import java.io.Serializable;

public class TAuthRolePms implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_role_pms.role_id
     *
     * @mbggenerated
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_role_pms.pms_id
     *
     * @mbggenerated
     */
    private Long pmsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_auth_role_pms
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_role_pms.role_id
     *
     * @return the value of t_auth_role_pms.role_id
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_role_pms.role_id
     *
     * @param roleId the value for t_auth_role_pms.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_role_pms.pms_id
     *
     * @return the value of t_auth_role_pms.pms_id
     *
     * @mbggenerated
     */
    public Long getPmsId() {
        return pmsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_role_pms.pms_id
     *
     * @param pmsId the value for t_auth_role_pms.pms_id
     *
     * @mbggenerated
     */
    public void setPmsId(Long pmsId) {
        this.pmsId = pmsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_role_pms
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleId=").append(roleId);
        sb.append(", pmsId=").append(pmsId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}