package com.carl.springmvc.model;

import java.io.Serializable;
import java.util.Date;

public class TAuthUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_user.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_user.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_user.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_user.disabled
     *
     * @mbggenerated
     */
    private Boolean disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_user.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_user.salt
     *
     * @mbggenerated
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_user.totp_secret
     *
     * @mbggenerated
     */
    private String totpSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_user.account_level
     *
     * @mbggenerated
     */
    private Integer accountLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_auth_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_user.id
     *
     * @return the value of t_auth_user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_user.id
     *
     * @param id the value for t_auth_user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_user.create_time
     *
     * @return the value of t_auth_user.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_user.create_time
     *
     * @param createTime the value for t_auth_user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_user.status
     *
     * @return the value of t_auth_user.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_user.status
     *
     * @param status the value for t_auth_user.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_user.account
     *
     * @return the value of t_auth_user.account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_user.account
     *
     * @param account the value for t_auth_user.account
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_user.disabled
     *
     * @return the value of t_auth_user.disabled
     *
     * @mbggenerated
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_user.disabled
     *
     * @param disabled the value for t_auth_user.disabled
     *
     * @mbggenerated
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_user.nick_name
     *
     * @return the value of t_auth_user.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_user.nick_name
     *
     * @param nickName the value for t_auth_user.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_user.password
     *
     * @return the value of t_auth_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_user.password
     *
     * @param password the value for t_auth_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_user.salt
     *
     * @return the value of t_auth_user.salt
     *
     * @mbggenerated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_user.salt
     *
     * @param salt the value for t_auth_user.salt
     *
     * @mbggenerated
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_user.totp_secret
     *
     * @return the value of t_auth_user.totp_secret
     *
     * @mbggenerated
     */
    public String getTotpSecret() {
        return totpSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_user.totp_secret
     *
     * @param totpSecret the value for t_auth_user.totp_secret
     *
     * @mbggenerated
     */
    public void setTotpSecret(String totpSecret) {
        this.totpSecret = totpSecret == null ? null : totpSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_user.account_level
     *
     * @return the value of t_auth_user.account_level
     *
     * @mbggenerated
     */
    public Integer getAccountLevel() {
        return accountLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_user.account_level
     *
     * @param accountLevel the value for t_auth_user.account_level
     *
     * @mbggenerated
     */
    public void setAccountLevel(Integer accountLevel) {
        this.accountLevel = accountLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createTime=").append(createTime);
        sb.append(", status=").append(status);
        sb.append(", account=").append(account);
        sb.append(", disabled=").append(disabled);
        sb.append(", nickName=").append(nickName);
        sb.append(", password=").append(password);
        sb.append(", salt=").append(salt);
        sb.append(", totpSecret=").append(totpSecret);
        sb.append(", accountLevel=").append(accountLevel);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}