package com.eif.fis.dal.model;

import java.io.Serializable;
import java.util.Date;

public class TFisResvProdMouldInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_mould_info.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_mould_info.product_id
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_mould_info.agreement_template_name
     *
     * @mbggenerated
     */
    private String agreementTemplateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_mould_info.agreement_template_id
     *
     * @mbggenerated
     */
    private String agreementTemplateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_mould_info.agreement_type
     *
     * @mbggenerated
     */
    private Byte agreementType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_mould_info.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_mould_info.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_mould_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_mould_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_fis_resv_prod_mould_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_mould_info.id
     *
     * @return the value of t_fis_resv_prod_mould_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_mould_info.id
     *
     * @param id the value for t_fis_resv_prod_mould_info.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_mould_info.product_id
     *
     * @return the value of t_fis_resv_prod_mould_info.product_id
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_mould_info.product_id
     *
     * @param productId the value for t_fis_resv_prod_mould_info.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_mould_info.agreement_template_name
     *
     * @return the value of t_fis_resv_prod_mould_info.agreement_template_name
     *
     * @mbggenerated
     */
    public String getAgreementTemplateName() {
        return agreementTemplateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_mould_info.agreement_template_name
     *
     * @param agreementTemplateName the value for t_fis_resv_prod_mould_info.agreement_template_name
     *
     * @mbggenerated
     */
    public void setAgreementTemplateName(String agreementTemplateName) {
        this.agreementTemplateName = agreementTemplateName == null ? null : agreementTemplateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_mould_info.agreement_template_id
     *
     * @return the value of t_fis_resv_prod_mould_info.agreement_template_id
     *
     * @mbggenerated
     */
    public String getAgreementTemplateId() {
        return agreementTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_mould_info.agreement_template_id
     *
     * @param agreementTemplateId the value for t_fis_resv_prod_mould_info.agreement_template_id
     *
     * @mbggenerated
     */
    public void setAgreementTemplateId(String agreementTemplateId) {
        this.agreementTemplateId = agreementTemplateId == null ? null : agreementTemplateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_mould_info.agreement_type
     *
     * @return the value of t_fis_resv_prod_mould_info.agreement_type
     *
     * @mbggenerated
     */
    public Byte getAgreementType() {
        return agreementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_mould_info.agreement_type
     *
     * @param agreementType the value for t_fis_resv_prod_mould_info.agreement_type
     *
     * @mbggenerated
     */
    public void setAgreementType(Byte agreementType) {
        this.agreementType = agreementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_mould_info.create_by
     *
     * @return the value of t_fis_resv_prod_mould_info.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_mould_info.create_by
     *
     * @param createBy the value for t_fis_resv_prod_mould_info.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_mould_info.update_by
     *
     * @return the value of t_fis_resv_prod_mould_info.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_mould_info.update_by
     *
     * @param updateBy the value for t_fis_resv_prod_mould_info.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_mould_info.create_time
     *
     * @return the value of t_fis_resv_prod_mould_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_mould_info.create_time
     *
     * @param createTime the value for t_fis_resv_prod_mould_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_mould_info.update_time
     *
     * @return the value of t_fis_resv_prod_mould_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_mould_info.update_time
     *
     * @param updateTime the value for t_fis_resv_prod_mould_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fis_resv_prod_mould_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", agreementTemplateName=").append(agreementTemplateName);
        sb.append(", agreementTemplateId=").append(agreementTemplateId);
        sb.append(", agreementType=").append(agreementType);
        sb.append(", createBy=").append(createBy);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}