package com.eif.fis.dal.dao;

import com.eif.fis.dal.model.TFisResvProdMouldInfo;
import java.util.List;

public interface TFisResvProdMouldInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fis_resv_prod_mould_info
     *
     * @mbggenerated
     */
    int insert(TFisResvProdMouldInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fis_resv_prod_mould_info
     *
     * @mbggenerated
     */
    List<TFisResvProdMouldInfo> selectAll();
}