package com.carl.springmvc.mapper;

import com.carl.springmvc.model.TAuthRolePms;
import java.util.List;

public interface TAuthRolePmsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_role_pms
     *
     * @mbggenerated
     */
    int insert(TAuthRolePms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_role_pms
     *
     * @mbggenerated
     */
    List<TAuthRolePms> selectAll();
}