package com.carl.springmvc.mapper;

import com.carl.springmvc.beans.User;
import com.carl.springmvc.model.TAuthUser;
import java.util.List;

public interface TAuthUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_user
     *
     * @mbggenerated
     */
    int insert(TAuthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_user
     *
     * @mbggenerated
     */
    List<TAuthUser> selectAll();


    List<TAuthUser> selectByName(String userName);
}