package com.carl.springmvc.mapper;

import com.carl.springmvc.model.TAuthUserRole;
import java.util.List;

public interface TAuthUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_user_role
     *
     * @mbggenerated
     */
    int insert(TAuthUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_user_role
     *
     * @mbggenerated
     */
    List<TAuthUserRole> selectAll();
}